      - name: Setup Git LFS and Clone Core Libraries
        run: |
          git lfs install
          rm -rf AndroidLibXrayLite
          git clone --depth=1 --recurse-submodules https://github.com/2dust/AndroidLibXrayLite.git AndroidLibXrayLite
          cd AndroidLibXrayLite
          git lfs pull
          find . -name ".git*" -exec rm -rf {} +
          cd ..
          # التحقق من أن حجم المكتبة حقيقي وليس مؤشر نصي
          ls -lh AndroidLibXrayLite/
